compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_moe_layer_cls_names: MixtralSparseMoeBlock
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: 10.123.18.157
main_process_port: 1234
main_training_function: main
mixed_precision: bf16
num_machines: 2
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
